backend:
  name: git-gateway
  branch: main
  squash_merges: true

publish_mode: editorial_workflow
show_preview_links: true

media_folder: 'src/_assets/img'
public_folder: '/assets/img'

site_url: 'https://gameworkerscoalition.org'

i18n:
  structure: multiple_folders
  locales: [en, de, fr]

collections:
  - label: 'Global Data'
    name: data
    editor:
      preview: false
    delete: false
    files:
      - label: 'Site Info'
        name: siteinfo
        file: 'src/_data/siteinfo.yaml'
        fields:
          - { name: title, widget: string }
          - { name: url, widget: string }
      - label: 'Organizations'
        name: orgs
        file: 'src/_data/orgs.yaml'
        fields:
          - label: 'Europe'
            name: europe
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }
          - label: 'North America (northam)'
            name: northam
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }
          - label: 'South America (southam)'
            name: southam
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }
          - label: 'Oceania'
            name: oceania
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }
          - label: 'Asia'
            name: asia
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }
          - label: 'Africa'
            name: africa
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }

  - label: 'Language Data'
    name: lang
    editor:
      preview: false
    delete: false
    i18n:
      structure: single_file
    files:
      - label: 'English'
        name: data-en
        file: 'src/en/en.yaml'
        i18n: true
        fields:
          - { name: langtag, widget: hidden, default: 'en' }
          - { label: 'Site Description', name: sitedescription, widget: string, i18n: true }
          - label: 'Localized strings'
            name: i18n
            widget: list
            collapsed: false
            summary: '{{fields.key}}: {{fields.t}}'
            i18n: true
            fields:
              - { label: 'Key', name: key, widget: string }
              - { label: 'Translation', name: t, widget: string }
      - label: 'Deutsch'
        name: data-de
        file: 'src/de/de.yaml'
        fields:
          - { name: langtag, widget: hidden, default: 'de' }
          - {
              label: 'Website-Beschreibung',
              name: sitedescription,
              widget: string,
            }
          - label: 'Lokalisierte Zeichenfolgen'
            name: i18n
            widget: list
            collapsed: false
            summary: '{{fields.key}}: {{fields.t}}'
            fields:
              - { label: 'Schlüssel', name: key, widget: string }
              - { label: 'Übersetzung', name: t, widget: string }
      - label: 'Français'
        name: data-fr
        file: 'src/fr/fr.yaml'
        fields:
          - { name: langtag, widget: hidden, default: 'fr' }
          - {
              label: 'Description du site',
              name: sitedescription,
              widget: string,
            }
          - label: 'Textes traduits'
            name: i18n
            widget: list
            collapsed: false
            summary: '{{fields.key}}: {{fields.t}}'
            fields:
              - { label: 'Clé', name: key, widget: string }
              - { label: 'Traduction', name: t, widget: string }

  - label: 'Pages'
    name: pages
    folder: 'src'
    identifier-field: name
    create: true
    i18n: true
    fields:
      - { label: 'Page name', name: name, widget: string, i18n: duplicate }
      - { label: 'Content', name: body, widget: markdown, modes: [raw], i18n: true }
