backend:
  name: git-gateway
  branch: main
  squash_merges: true

publish_mode: editorial_workflow
show_preview_links: true

media_folder: 'src/_assets/img'
public_folder: '/assets/img'

site_url: 'https://gameworkerscoalition.org'

collections:
  - label: 'Global Data'
    name: data
    delete: false
    files:
      - label: 'Site Info'
        name: siteinfo
        file: 'src/_data/siteinfo.yaml'
        fields:
          - { label: 'Title', name: title, widget: string }
          - { label: 'Url', name: url, widget: string }
      - label: 'Organizations'
        name: orgs
        file: 'src/_data/orgs.yaml'
        fields:
          - label: 'Regions'
            name: regions
            widget: list
            fields:
              - label: 'Region tag'
                name: regiontag
                widget: select
                options: ['africa', 'asia', 'na', 'sa', 'europe', 'oceania']
              - label: 'Region orgs'
                name: regionorgs
                widget: list
                fields:
                  - { label: 'Organization name', name: name, widget: string }
                  - {
                      label: 'Location',
                      name: location,
                      widget: string,
                      required: false,
                    }
                  - { label: 'Link', name: link, widget: string }

  - label: 'Language Data'
    name: lang
    delete: false
    files:
      - label: 'English'
        name: data-en
        file: 'src/en/en.yaml'
        fields:
          - { label: 'lang', name: langtag, widget: hidden, default: 'en' }
          - { label: 'Site Description', name: sitedesc, widget: string }
          - label: 'i18n'
            name: i18n
            widget: list
            fields:
              - { label: 'Key', name: i18nkey, widget: string }
              - { label: 'Translation', name: i18nt, widget: string }

  - label: 'Content: English'
    name: content-en
    folder: 'src/en/content'
    identifier_field: name
    create: true
    fields:
      - { label: 'Name', name: name, widget: string }
      - { label: 'Content', name: content, widget: markdown }
