backend:
  name: git-gateway
  branch: main
  squash_merges: true

publish_mode: editorial_workflow
show_preview_links: true

media_folder: 'src/_assets/img'
public_folder: '/assets/img'

site_url: 'https://gameworkerscoalition.org'

i18n:
  structure: multiple_folders
  locales: [en, de, fr]

collections:
  - label: 'Global Data'
    name: data
    editor:
      preview: false
    delete: false
    files:
      - label: 'Site Info'
        name: siteinfo
        file: 'src/_data/siteinfo.yaml'
        fields:
          - { name: title, widget: string }
          - { name: url, widget: string }
      - label: 'Organizations'
        name: orgs
        file: 'src/_data/orgs.yaml'
        fields:
          - label: 'Europe'
            name: europe
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }
          - label: 'North America (northam)'
            name: northam
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }
          - label: 'South America (southam)'
            name: southam
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }
          - label: 'Oceania'
            name: oceania
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }
          - label: 'Asia'
            name: asia
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }
          - label: 'Africa'
            name: africa
            widget: list
            summary: '{{fields.name}} | {{fields.location}} {{fields.link}}'
            fields:
              - { name: name, widget: string }
              - {
                  name: location,
                  widget: string,
                  required: false,
                }
              - { name: link, widget: string }
  
  - label: 'Language Data'
    name: i18n
    folder: 'src/_i18n'
    extension: yaml
    editor:
      preview: false
    delete: false
    i18n:
      structure: multiple_files
    fields:
      - { name: title, widget: hidden }
      - label: 'Localized strings'
        label_singular: 'string'
        name: data
        widget: list
        summary: '{{fields.key}}: {{fields.t}}'
        create: true
        i18n: true
        fields:
          - { label: 'Key', name: key, widget: string }
          - { label: 'Translation', name: t, widget: string }

  - label: 'Pages'
    name: pages
    folder: 'src'
    extension: md
    identifier-field: name
    create: true
    delete: false
    i18n: true
    fields:
      - { label: 'Page name', name: name, widget: string, i18n: duplicate }
      - { label: 'Content', name: body, widget: markdown, modes: [raw], i18n: true }
