backend:
  name: git-gateway
  branch: main
  squash_merges: true

publish_mode: editorial_workflow
show_preview_links: true

media_folder: 'src/_assets/img'
public_folder: '/assets/img'

site_url: 'https://gameworkerscoalition.org'

i18n:
  structure: multiple_folders
  locales: [en, de, fr]

collections:
  - label: 'Global Data'
    name: data
    editor:
      preview: false
    delete: false
    files:
      - label: 'Site Info'
        name: siteinfo
        file: 'src/_data/siteinfo.yaml'
        fields:
          - { label: 'Title', name: title, widget: string }
          - { label: 'Url', name: url, widget: string }
      - label: 'Organizations'
        name: orgs
        file: 'src/_data/orgs.yaml'
        fields:
          - label: 'Regions'
            name: regions
            widget: list
            summary: '{{fields.name | upper}} orgs'
            fields:
              - label: 'Region tag'
                name: name
                widget: select
                options: ['africa', 'asia', 'northam', 'southam', 'europe', 'oceania']
              - label: 'Region orgs'
                name: orgs
                widget: list
                summary: '{{fields.name}} ({{fields.link}})'
                fields:
                  - { label: 'Organization name', name: name, widget: string }
                  - {
                      label: 'Location',
                      name: location,
                      widget: string,
                      required: false,
                    }
                  - { label: 'Link', name: link, widget: string }

  - label: 'Language Data'
    name: lang
    editor:
      preview: false
    delete: false
    files:
      - label: 'English'
        name: data-en
        file: 'src/en/en.yaml'
        fields:
          - { label: 'lang', name: langtag, widget: hidden, default: 'en' }
          - { label: 'Site Description', name: sitedescription, widget: string }
          - label: 'Localized strings'
            name: i18n
            widget: list
            summary: '{{fields.key}}: {{fields.t}}'
            fields:
              - { label: 'Key', name: key, widget: string }
              - { label: 'Translation', name: t, widget: string }
      - label: 'Deutsch'
        name: data-de
        file: 'src/de/de.yaml'
        fields:
          - { label: 'lang', name: langtag, widget: hidden, default: 'de' }
          - {
              label: 'Website-Beschreibung',
              name: sitedescription,
              widget: string,
            }
          - label: 'Lokalisierte Zeichenfolgen'
            name: i18n
            widget: list
            summary: '{{fields.key}}: {{fields.t}}'
            fields:
              - { label: 'Schlüssel', name: key, widget: string }
              - { label: 'Übersetzung', name: t, widget: string }
      - label: 'Français'
        name: data-fr
        file: 'src/fr/fr.yaml'
        fields:
          - { label: 'lang', name: langtag, widget: hidden, default: 'fr' }
          - {
              label: 'Description du site',
              name: sitedescription,
              widget: string,
            }
          - label: 'Textes traduits'
            name: i18n
            widget: list
            summary: '{{fields.key}}: {{fields.t}}'
            fields:
              - { label: 'Clé', name: key, widget: string }
              - { label: 'Traduction', name: t, widget: string }

  - label: 'Pages'
    name: pages
    folder: 'src'
    filter: { field: 'pagefile', value: 'true' }
    identifier-field: name
    create: true
    i18n: true
    fields:
      - { label: 'Page name', name: name, widget: string, i18n: duplicate }
      - { label: 'Content', name: body, widget: markdown }
