backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
show_preview_links: true

media_folder: "src/assets/img"
public_folder: "/assets/img"

site_url: https://cosmogr.am

# Please run "npx netlify-cms-proxy-server" for local backend
# local_backend: true

collections:
  - label: "Posts"
    name: "posts"
    label_singular: "post"
    folder: "src/_posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    publish: false
    delete: false
    editor:
      preview: false
    files:
      - label: "Info"
        name: "info"
        file: "src/_data/siteinfo.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Twitter, name: twitter, widget: string }
